image: maven:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd calendar
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - fxui/target/*.jar

test:
  stage: test
  script:
    - echo "Building project with maven"
    - cd calendar
    - mvn verify
    - cat fxui/target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    when: always
    reports:
      junit: fxui/target/surefire-reports/TEST-*.xml
