image: maven:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd calendar
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - core/target/*.jar

maven_build:
  stage: test
  script:
    - echo "Building project with maven"
    - cd calendar
    - mvn verify
